# Generated by Django 3.2.8 on 2021-10-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='verify',
            name='phone_number',
            field=models.CharField(default=111, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='price',
            field=models.IntegerField(),
        ),
    ]
