# Generated by Django 3.2.8 on 2021-10-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211029_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verify',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
